### ISSUE TITLE
Could you please explain to me how change the folder colors everywhere?

### ISSUE THREAD

**Issue by koesherbacon** [manjaro/artwork-numix-reborn-manjaro-themes#2]
Right now my folders are all green, which I suspect is the default setting.  I see that there's many other colors available so I'm hoping you can explain how I can change it from its Green default to Purple (my favorite color)

Thanks a lot!

:+1:

**Comment by oberon2007** [comment]
Hi there!
Numix Reborn theme does not offer any color variations. It's a green theme! ;)

**Comment by oberon2007** [comment]
I see what you mean: the colored folders I think are either leftovers from previous versions - or they have to be invoked by their names by applications ... I think

**Comment by oberon2007** [comment]
You will have to actually rename the files for example *.svg -> green-*.svg and blue-*.svg -> *.svg

**Comment by koesherbacon** [comment]
Just so I'm clear, I should find the default green ones, back them up as a different name (just to be safe) and then rename the purple folders (or whatever color) the same as the original green ones?  

(Sorry, I have dyslexia, so it's sometimes difficult for me to envision what I'm reading without making sure I fully understood.)

Thanks!

**Comment by oberon2007** [comment]
Yes. The files without a color at the beginning of the file-names are the ones that actually get used :)
So you could rename for example **folder.svg** -> **green-folder.svg** and then **purple-folder.svg** -> **folder.svg**
That should work! :)
